### PR TITLE
add config item 'groups_include_regex' to specify a filter for groups

### PR DESCRIPTION
**Pull request by fasihi01**
Hi,
thank you for your great work with this iptv-proxy. 
I needed a way to minimize the proxied playlist, so i've introduced the groups_include_regex which because it fitted my needs best.
Feel free to accept or reject.

Have a nice day!

### CODE REVIEW

**Comment by kvaster** [comment]
The idea is OK, but code is not.
* Bad formatting
* Using iterator directly

I will try to prepare example how it should look like.

**Comment by fasihi01** [comment]
- The formatting does not fit in with the rest of the code, didn't consider this. 
- I prefer iterators over lambdas, because lambdas / inner functions compile to a larger footprint. But thats a question of personal preference, and it's your project of course :)
- Maybe my solution is to specific to be useful for other users. So if you want to drop the pull request, it'd be totally ok for me.

**Comment by kvaster** [comment]
Added support for filtering channel by group. This is how I would like to see it: https://github.com/kvaster/iptv-proxy/commit/41659488ecf90b54f58f166fcbc23460aa87afc0

Always open to PRs and ideas :)

**Comment by fasihi01** [comment]
Well done, thank you!

**Pull request closed without merging**
